### ISSUE TITLE
Missing /dist/site.css & main.js

### ISSUE THREAD

**Issue by ahukgit** [elucidsoft/aspnetcore-Vue-starter-signalR#2]
After doing a restore, npm install, build and run the vendor files correctly get created inside the wwwroot/dist but no site.css and main.js is created.

Then we get the error on dev tools:

```
GET http://node27.codenvy.io:41656/dist/site.css net::ERR_ABORTED
node27.codenvy.io/:23 GET http://node27.codenvy.io:41656/dist/main.js net::ERR_ABORTED
node27.codenvy.io/:23 GET http://node27.codenvy.io:41656/dist/main.js 404 (Not Found)
```

**Comment by elucidsoft** [comment]
Can you try running `webpack --config webpack.config.vendor.js` in the root directory?

**Comment by ahukgit** [comment]
I get `bash: webpack: command not found` which is strange

**Comment by ahukgit** [comment]
Okay I managed to get a main.js created using `npm run build` , however I still have no site.css

**Comment by elucidsoft** [comment]
I will look into the site.css issue

**Comment by ahukgit** [comment]
Thanks, I still haven't managed to get the site.css to build

**Comment by elucidsoft** [comment]
I don't see any issues.  Can you explain to me exactly what your doing? The site.css is part of the webpack configuration in webpack.config.js, it uses the css-loader plugin.  I pulled a fresh copy of this template down and it is working fine for me.  What is the exact error its giving you when you build?
