### ISSUE TITLE
Bootstrap JS not Loaded by Default

### ISSUE THREAD

**Issue by greenec** [elucidsoft/aspnetcore-Vue-starter-signalR#3]
After getting the app up and running, I noticed that the bootstrap JS was being loaded in the webpacked `vendor.js` file, but I wasn't getting the bootstrap functionality for things like the collapsing navbar on mobile.

After adding `import 'bootstrap'` to the `app.js` file, the collapsing navbar started to work.

I'm not sure if `app.js` is the proper place for this, or if it should be somewhere like `boot-app.js` instead.

This issue happened on the 3 machines that I tested after pulling a fresh copy of the repository, but adding `import 'bootstrap'` seems to be a reasonable fix for the issue.

**Comment by elucidsoft** [comment]
Can you submit a pull request so I can merge the change in?

**Comment by greenec** [comment]
I'd be happy to do that, but I just want to make sure that, conceptually, putting it in `app.js` is the right place to do it. `boot-app.js` loads `app.js`, so I wasn't sure if it would make more sense to have it in `boot-app.js` instead.

Also, jQuery is not exposed to the window (globally) by default either. I've added a few lines that look like 
`import jquery from 'jquery';`
`window.$ = jquery`
`window.jQuery = jquery;`
in order for plugins like `jquery-validate` to have access to jQuery.

If app.js is the right place for these changes, I'll make a pull request for you to merge the change in.

Thanks!

**Comment by elucidsoft** [comment]
I think app.js is fine, I see how it can be argued either way. For jQuery
the Vue documentation has specifically guidance on how to properly
integrate it, not sure if it covers what you did or not but might want to
take a look at it to make sure.

**Comment by greenec** [comment]
I've looked at quite a few webpack examples, and it seems like what you did with
`new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' })`
should have been enough, but I could never get that to expose jQuery at the global level.

The pull request that I'm creating has the solution which loads it and creates two global variables which reference the module, as well as loading the bootstrap scripts.

**Comment by greenec** [comment]
Resolved in the pull request.
